### ISSUE TITLE
Fix the failing travis tests!

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [developer-student-club-thapar/botsFramework#150]
- travis tests fail for files in the telegram folder.

**Comment by raghavTinker** [comment]
Can I have a look into this
I have knowledge in using the telegram-bot api in python

**Comment by Saurav-Shrivastav** [comment]
Yeah @raghavTinker, I'll assign it to you.

**Comment by raghavTinker** [comment]
> Yeah @raghavTinker, I'll assign it to you.

Where is this travis bug located btw in the repo?

**Comment by raghavTinker** [comment]
I also couldnt help notice but your telegram bit is empty. Can I work on it with you guys?

**Comment by specter25** [comment]
@raghavTinker do you have any knowledge about pre-commit hooks ?

**Comment by raghavTinker** [comment]
No I don’t



Sent from Yahoo Mail for iPhone


On Tuesday, October 6, 2020, 9:07 PM, Ujjwal Agarwal <notifications@github.com> wrote:




@raghavTinker do you have any knowledge about pre-commit hooks ?

**Comment by raghavTinker** [comment]
Hi can someone help me out?

**Comment by specter25** [comment]
@Saurav-Shrivastav i believe you will have to fix this issue , @raghavTinker you can work in collab with @Saurav-Shrivastav on this one. Approach him on discord.
